# todo: revist values names once we register more then one cronjob concurrently
{{- if and $.Values.audience $.Values.auth0Domain $.Values.clientId $.Values.googleClientEmail $.Values.clientSecret $.Values.googlePrivateKey }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: metrics-sheet
  namespace: {{ $.Values.namespace | default "mds" }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: metrics-sheet
            image: busybox
            env:
            - name: AUDIENCE
              value: {{ $.Values.audience }}
            - name: AUTH0_DOMAIN
              value: {{ $.Values.auth0Domain }}
            - name: CLIENT_ID
              value: {{ $.Values.clientId }}
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: metrics-sheet
                  key: CLIENT_SECRET
            - name: GOOGLE_CLIENT_EMAIL
              value: {{ $.Values.googleClientEmail }}
            - name: GOOGLE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: metrics-sheet
                  key: GOOGLE_PRIVATE_KEY
            restartPolicy: OnFailure
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-sheet
  namespace: {{ $.Values.namespace | default "mds" }}
type: Opaque
data:
  CLIENT_SECRET: {{ $.Values.clientSecret | b64enc }}
  GOOGLE_PRIVATE_KEY: {{ $.Values.googlePrivateKey | b64enc }}
{{- end}}