{{- range $name, $api := .Values.apis }}
{{- if $api.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mds.fullname" $ }}-{{ $name }}-{{ $api.version }}-service
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ include "mds.fullname" $ }}-{{ $api.name }}-{{ $api.version }}
  ports:
  -
    name: http-{{ $name }}
    port: 4000
{{- end }}
{{- end }}
