{{- range $name, $api := .Values.apis }}
{{- if $api.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace | default "mds" }}
spec:
  selector:
    app: {{ $name }}
  ports:
  -
    name: http-{{ $name }}
    port: 4000
{{- end }}
{{- end }}
