apiVersion: eventing.knative.dev/v1alpha1
kind: Broker
metadata:
  name: natss
#  namespace: {{ $.Release.Namespace }}
spec:
  channelTemplateSpec:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: NatssChannel
#    kind: ClusterChannelProvisioner
#    name: natss
